export const pratosBanco = [
{ id: 1, nome: 'arroz', preco: '12.99', linkDaImagem: 'abcdef' },
{ id: 2, nome: 'Spaghetti Carbonara', preco: '12.99', linkDaImagem: 'https://example.com/spaghetti.jpg' },
{ id: 3, nome: 'Caesar Salad', preco: '8.49', linkDaImagem: 'https://example.com/caesar.jpg' },
{ id: 4, nome: 'Grilled Chicken', preco: '14.99', linkDaImagem: 'https://example.com/chicken.jpg' },
{ id: 5, nome: 'Margherita Pizza', preco: '10.99', linkDaImagem: 'https://example.com/pizza.jpg' },
{ id: 6, nome: 'Tiramisu', preco: '6.49', linkDaImagem: 'https://example.com/tiramisu.jpg' },
{ id: 7, nome: 'Feijoada', preco: '19.99', linkDaImagem: 'https://example.com/feijoada.jpg' },
{ id: 8, nome: 'Coxinha', preco: '4.99', linkDaImagem: 'https://example.com/coxinha.jpg' },
{ id: 9, nome: 'Pão de Queijo', preco: '3.49', linkDaImagem: 'https://example.com/pao_de_queijo.jpg' },
{ id: 10, nome: 'Açai', preco: '7.99', linkDaImagem: 'https://example.com/acai.jpg' },
{ id: 11, nome: 'Churrasco', preco: '29.99', linkDaImagem: 'https://example.com/churrasco.jpg' },
{ id: 12, nome: 'Brigadeiro', preco: '2.49', linkDaImagem: 'https://example.com/brigadeiro.jpg' },
{ id: 13, nome: 'Pastel', preco: '5.99', linkDaImagem: 'https://example.com/pastel.jpg' },
{ id: 14, nome: 'Moqueca', preco: '24.99', linkDaImagem: 'https://example.com/moqueca.jpg' },
{ id: 15, nome: 'Cuscuz', preco: '6.49', linkDaImagem: 'https://example.com/cuscuz.jpg' },
{ id: 16, nome: 'Bolo de Rolo', preco: '8.99', linkDaImagem: 'https://example.com/bolo_de_rolo.jpg' },
{ id: 17, nome: 'Empada', preco: '4.49', linkDaImagem: 'https://example.com/empada.jpg' },
{ id: 18, nome: 'Vatapá', preco: '18.49', linkDaImagem: 'https://example.com/vatapa.jpg' },
{ id: 19, nome: 'Quindim', preco: '3.99', linkDaImagem: 'https://example.com/quindim.jpg' },
{ id: 20, nome: 'Tacacá', preco: '12.99', linkDaImagem: 'https://example.com/tacaca.jpg' },
{ id: 21, nome: 'Escondidinho', preco: '14.99', linkDaImagem: 'https://example.com/escondidinho.jpg' },
];
